# Generated by Django 3.2.7 on 2021-09-29 17:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('capa', models.FileField(unique=True, upload_to='C:\\Users\\clcos\\Documents\\Scripts\\site_portfolio\\portfolio_django\\portfolio\\home\\dynamic\\img')),
                ('iframe_video', models.TextField(unique=True)),
                ('link_codigo', models.URLField(default='https://github.com/clcosta/', unique=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
