# Generated by Django 3.2.7 on 2021-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(unique=True, upload_to='C:\\Users\\clcos\\Documents\\Scripts\\site_portfolio\\portfolio_django\\portfolio\\home\\dynamic\\home\\uploads/<filename>'),
        ),
    ]
