# Generated by Django 3.2.7 on 2021-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projeto_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
