"""empty message

Revision ID: 16b3261aef79
Revises: 
Create Date: 2021-10-03 13:16:13.076792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b3261aef79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('capa', sa.String(), nullable=False),
    sa.Column('iframe_video', sa.Text(), nullable=False),
    sa.Column('link_codigo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capa'),
    sa.UniqueConstraint('iframe_video'),
    sa.UniqueConstraint('link_codigo'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    # ### end Alembic commands ###
